IP_NW = "192.168.7."
JENKINS_MASTER_IP = 10
JENKINS_JAVA_SLAVE_IP = 14
JENKINS_NODE_SLAVE_IP = 15
JENKINS_PYTHON_SLAVE_IP = 16
NEXUS_NODE_IP = 17
SONARQUBE_NODE_IP = 18
DOCKER_NODE_IP = 20
ELK_NODE_IP = 21

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "jenkins-master" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins-master"
            vb.memory = 1024
            vb.cpus = 2
        end
        node.vm.hostname = "jenkins-master"
        node.vm.network :private_network, ip: IP_NW + "#{JENKINS_MASTER_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2710
        node.vm.network "forwarded_port", guest: 8080, host: 8099

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
        node.vm.provision "CreateUnixUsers", type: "shell", :path => "centos/createUnixUsers.sh"
        node.vm.provision "installJenkins", type: "shell", :path => "centos/installJenkins.sh"
		node.vm.provision "installGit", type: "shell", :path => "centos/installGIT.sh"
    end
    config.vm.define "jenkins-java-node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins-java-node"
            vb.memory = 1500
            vb.cpus = 2
        end
        node.vm.hostname = "jenkins-java-node"
        node.vm.network :private_network, ip: IP_NW + "#{JENKINS_JAVA_SLAVE_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2718
        node.vm.network "forwarded_port", guest: 3306, host: 8888

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
        node.vm.provision "CreateUnixUsers", type: "shell", :path => "centos/createUnixUsersinJenkinsJavaSlave.sh"
        node.vm.provision "installJava", type: "shell", :path => "centos/installJava.sh"
        node.vm.provision "installMariaDB", type: "shell", :path => "centos/installMariaDB.sh"
		node.vm.provision "installGit", type: "shell", :path => "centos/installGIT.sh"
		node.vm.provision "installDocker", type: "shell", :path => "centos/install-docker.sh"
    end
    config.vm.define "jenkins-nodejs-node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins-nodejs-node"
            vb.memory = 1500
            vb.cpus = 1
        end
        node.vm.hostname = "jenkins-nodejs-node"
        node.vm.network :private_network, ip: IP_NW + "#{JENKINS_NODE_SLAVE_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2719
        node.vm.network "forwarded_port", guest: 27017, host: 27017

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
        node.vm.provision "CreateUnixUsers", type: "shell", :path => "centos/createUnixUsersinJenkinsNodeSlave.sh"
        node.vm.provision "installNode", type: "shell", :path => "centos/installNode.sh"
        node.vm.provision "installMongoDB", type: "shell", :path => "centos/installMongoDB.sh" do |s|
            s.args = ["7"]
		end
		node.vm.provision "installGit", type: "shell", :path => "centos/installGIT.sh"
		node.vm.provision "installDocker", type: "shell", :path => "centos/install-docker.sh"
    end
    config.vm.define "jenkins-python-node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins-python-node"
            vb.memory = 1500
            vb.cpus = 1
        end
        node.vm.hostname = "jenkins-python-node"
        node.vm.network :private_network, ip: IP_NW + "#{JENKINS_PYTHON_SLAVE_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2720
        node.vm.network "forwarded_port", guest: 5432, host: 5435

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
        node.vm.provision "CreateUnixUsers", type: "shell", :path => "centos/createUnixUsersinJenkinsPythonSlave.sh"
		node.vm.provision "installPython3", type: "shell", :path => "centos/installPython3.sh"
        node.vm.provision "installPostgres11", type: "shell", :path => "centos/installPostgressDB.sh"
		node.vm.provision "installGit", type: "shell", :path => "centos/installGIT.sh"
		node.vm.provision "installDocker", type: "shell", :path => "centos/install-docker.sh"
    end
    config.vm.define "nexus-node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "nexus-node"
            vb.memory = 3000
            vb.cpus = 2
        end
        node.vm.hostname = "nexus-node"
        node.vm.network :private_network, ip: IP_NW + "#{NEXUS_NODE_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2740
        node.vm.network "forwarded_port", guest: 8081, host: 8098

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
        node.vm.provision "installNexus", type: "shell", :path => "centos/installNexus.sh"
    end
    config.vm.define "sonarqube-node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "sonarqube-node"
            vb.memory = 2400
            vb.cpus = 1
        end
        node.vm.hostname = "sonarqube-node"
        node.vm.network :private_network, ip: IP_NW + "#{SONARQUBE_NODE_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2750
        node.vm.network "forwarded_port", guest: 9000, host: 8097

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
        node.vm.provision "installSonar", type: "shell", :path => "centos/installSonar.sh"
    end
    config.vm.define "docker-node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "docker-node"
            vb.memory = 2000
            vb.cpus = 2
        end
        node.vm.hostname = "docker-node"
        node.vm.network :private_network, ip: IP_NW + "#{DOCKER_NODE_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2777
        node.vm.network "forwarded_port", guest: 3306, host: 8068
        node.vm.network "forwarded_port", guest: 8000, host: 6999

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
		node.vm.provision "installDocker", type: "shell", :path => "centos/install-docker.sh"
    end
    config.vm.define "elk-node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "elk-node"
            vb.memory = 4000
            vb.cpus = 2
        end
        node.vm.hostname = "elk-node"
        node.vm.network :private_network, ip: IP_NW + "#{ELK_NODE_IP}"
        node.vm.network "forwarded_port", guest: 22, host: 2760
        node.vm.network "forwarded_port", guest: 3306, host: 8096
        node.vm.network "forwarded_port", guest: 9200, host: 9200
        node.vm.network "forwarded_port", guest: 5601, host: 5601

        node.vm.provision "setup-hosts", :type => "shell", :path => "centos/setup-hosts.sh" do |s|
            s.args = ["eth1"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "centos/update-dns.sh"
        node.vm.provision "installJava", type: "shell", :path => "centos/installJava.sh"
        node.vm.provision "installELK7x", type: "shell", :path => "centos/installELK7x.sh"
    end
end